stages:
  - build

docker-with-buildx:
  stage: build
  image: jdrouet/docker-with-buildx
  services:
    - docker:dind
  parallel:
    matrix:
      - BUILDX_VERSION:
          - v0.5.1
          - v0.5.0
          - v0.4.2
          - v0.4.1
          - v0.4.0
        DOCKER_VERSION:
          - latest
          - "20"
          - "20.10"
          - 20.10.7
          - "19"
          - "19.03"
          - 19.03.15
  script:
    - docker buildx build --build-arg BUILDX_VERSION=${BUILDX_VERSION} --build-arg DOCKER_VERSION=${DOCKER_VERSION} --tag jdrouet/docker-with-buildx:${DOCKER_VERSION}-${BUILDX_VERSION} docker-with-buildx

