name: build tor-proxy docker images

on:
  push:
    branches:
      - master
    paths:
      - 'tor-proxy/*'

jobs:
  build-image:
    name: build tor-proxy images and push
    runs-on: ubuntu-latest

    steps:

      - name: install qemu
        run: docker run --rm --privileged hypriot/qemu-register

      - name: checkout
        uses: actions/checkout@v1

      - name: login to docker hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: install buildx
        run: make buildx-install

      - name: build and push
        run: make -C tor-proxy buildx-push
